name: ShopGUI-
main: ItzFabb\Shop\Main
api: 3.22.2
version: 7
author: ItzFabb , updated by 
depend: ["EconomyAPI", "InvCrashFix"]

commands:
  shop:
    description: "buy items here!"
    permission: "use.shop.menu"
