name: ShopGUI-
main: ItzFabb\Shop\Main
api: 3.00.0
version: 7
author: Prince
depend: ["EconomyAPI", "InvCrashFix"]

commands:
  shop:
    description: "opens shop!"
    permission: "use.shop.menu"
