name: ShopGUI-
main: ItzFabb\Shop\Main
api: 3.22.2
version: 7
author: ItzFabb , Prince
depend: ["EconomyAPI", "InvCrashFix"]

commands:
  shop:
    description: "opens shop!"
    permission: "use.shop.menu"
